name: Build and upload Tempo package for POSIX platforms
on:
  push:
    branches:
      - master

jobs:

  build-posix:
    uses: ./.github/workflows/build-package.yml

    strategy:
      matrix:
        platform: [
          ubuntu2404-arm64-debug: {
              build_type: "Debug",
              build_runner: "ubuntu-24.04-arm",
              conan_profile: "Ubuntu24.04-armv8-Debug",
              install_dependencies_script: "sudo apt-get install clang autoconf automake libtool"
          },
          macos-arm64-debug: {
              build_type: "Debug",
              build_runner: "macos-15",
              conan_profile: "MacOS-armv8-Debug",
              install_dependencies_script: "brew install autoconf automake libtool"
          }
        ]

    secrets: inherit
    with:
      build_type: ${{ matrix.platform.build_type }}
      build_runner: ${{ matrix.platform.build_runner }}
      conan_profile: ${{ matrix.platform.conan_profile }}
      install_dependencies_script: ${{ matrix.platform.install_dependencies_script }}